version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lol
      POSTGRES_USER: lol
      POSTGRES_PASSWORD: lol
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-container
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres
    volumes:
      - ./src:/app/src
