version: '3'

services:
  lol-integration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lol-integration
    ports:
      - 3000:3000
    links:
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      POSTGRES_DB: lol
      POSTGRES_USER: lol
      POSTGRES_PASSWORD: lol
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  postgres:
    image: "postgres:16"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: lol
      POSTGRES_USER: lol
      POSTGRES_PASSWORD: lol
