version: '3'

networks:
  - default

services:
  lol-integration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lol-integration
    ports:
      - 3000:3000
    links:
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      POSTGRES_DB: lol
      POSTGRES_USER: lol
      POSTGRES_PASSWORD: lol
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - mynetwork

  redis:
    image: redis
    container_name: redis
    hostname: redis
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    ports:
        - '6379:6379'
    networks:
      - mynetwork

  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: lol
      POSTGRES_USER: lol
      POSTGRES_PASSWORD: lol
    networks:
      - mynetwork
