version: '3'

services:
  lol-integration:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: lol-integration
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - /src/node_modules
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - postgres
    links:
      - redis
    networks:
      - mynetwork

  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    networks:
      - mynetwork

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=lol
      - POSTGRES_USER=lol
      - POSTGRES_PASSWORD=lol
    ports:
      - '5432:5432'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
