version: '3'

services:
  redis:
    image: redis

  postgres:
    image: "postgres:16"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: lol
      POSTGRES_USER: lol
      POSTGRES_PASSWORD: lol
  
  lol-integration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lol-integration
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_DB: lol
      POSTGRES_USER: lol
      POSTGRES_PASSWORD: lol
      REDIS_HOST: redis
      REDIS_PORT: 6379