name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t vwijaya08/lol-integration .
      - name: Publish image to Docker Hub
        run: docker push vwijaya08/lol-integration:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Pull Docker image
        run: docker pull vwijaya08/lol-integration:latest

      - name: Stop and Remove old container (if exists)
        run: docker stop lol-integration || true && docker rm lol-integration || true

      - name: Run Docker container
        run: docker run --env RIOT_API_KEY=${{ secrets.RIOT_API_KEY }} -d -p 3000:3000 --name lol-integration vwijaya08/lol-integration
