name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t vwijaya08/lol-integration .
      - name: Publish image to docker hub
        run: docker push vwijaya08/lol-integration:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull vwijaya08/lol-integration:latest
      - name: Delete old container
        run: docker rm -f lol-integration
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name lol-integration vwijaya08/lol-integration